import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The portal is organised by PRODUCT, the way the integrator buys and the
 * dashboard names them (decision of the `portada-por-productos` change, modelled
 * on a payments developer portal: Inicio, Inicio rápido, then one entry per
 * product with an icon and a one-line description).
 *
 * `saas/1platform-api` is autogenerated: its two top-level docs (Inicio and
 * Inicio rápido, ordered by `sidebar_position`) come first, then one category per
 * product folder, then Plataforma and Convenciones. A product's label, icon and
 * description live in its `_category_.json` under `customProps`; its `index.mdx`
 * is the category's landing page. Atlas is a separate, standalone product, so it
 * closes the list as a single category of its own. Do not hardcode documents.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'autogenerated', dirName: 'saas/1platform-api'},
    {
      type: 'category',
      label: 'Atlas API',
      className: 'sidebar-product',
      customProps: {icon: 'layers', description: 'API independiente de entrega de contenido multitenant.'},
      link: {type: 'doc', id: 'saas/atlas-api/overview'},
      items: [{type: 'autogenerated', dirName: 'saas/atlas-api'}],
    },
  ],
};

export default sidebars;
