import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Single-audience information architecture: this portal documents how to
 * integrate with the 1Platform APIs from the outside. Nothing else.
 *
 * The former `Productos (por tenant)` group — 65 pages written for non-technical
 * operators configuring a workspace — was withdrawn by the
 * `docs-developer-minimalista` epic (decision D-1): a reader who arrives to
 * integrate had to discard 55% of the portal before finding anything for them.
 * Those URLs are 301'd; the content is one `git revert` away.
 *
 * With one audience left, the `SaaS y API` wrapper stopped ordering anything, so
 * the two API products are now top-level categories. Each is **autogenerated**;
 * its label, icon and description live in the section's `_category_.json` (the
 * DocSidebarItem/Category swizzle reads `customProps.{icon,description}`, where
 * `icon` is a name from src/components/Icon/icons.ts).
 * Each section's `index.mdx` is the category **index page**: per the Docusaurus
 * category-index convention it is auto-linked from the category header (so
 * clicking the product name goes straight to its Overview) and removed from the
 * item list (no duplicate "Overview" entry). The remaining pages are ordered by
 * per-page `sidebar_position` frontmatter.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      id: 'intro',
      className: 'sidebar-overview',
    },
    {type: 'autogenerated', dirName: 'saas'},
  ],
};

export default sidebars;
