import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Two-audience information architecture:
 *  - Products (per tenant) — non-technical operator docs for the configurable end-products.
 *  - SaaS & API — developer docs for building on the 1Platform infrastructure.
 *
 * Each product is an autogenerated category driven by per-page `sidebar_position`
 * frontmatter (overview = position 1).
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Products (per tenant)',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '1Platform Dashboard',
          items: [{type: 'autogenerated', dirName: 'products/dashboard'}],
        },
        {
          type: 'category',
          label: 'Atlas Dashboard',
          items: [{type: 'autogenerated', dirName: 'products/atlas-dashboard'}],
        },
        {
          type: 'category',
          label: 'Atlas App',
          items: [{type: 'autogenerated', dirName: 'products/atlas-app'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'SaaS & API',
      collapsed: false,
      items: [
        'saas/api-reference-index',
        {
          type: 'category',
          label: '1Platform API',
          items: [{type: 'autogenerated', dirName: 'saas/1platform-api'}],
        },
        {
          type: 'category',
          label: 'Atlas API',
          items: [{type: 'autogenerated', dirName: 'saas/atlas-api'}],
        },
      ],
    },
  ],
};

export default sidebars;
